services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=hadoopsample
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.2

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CLUSTER_NAME=hadoopsample
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs_datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.3

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CLUSTER_NAME=hadoopsample
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs_datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.4

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    environment:
      - CLUSTER_NAME=hadoopsample
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs_datanode3:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.5

  spark-master:
    build: ./spark
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master", "--port", "7077", "--webui-port", "8080"]
    ports:
      - "8080:8080"
      - "4040-4045:4040-4045"
      - "7077:7077"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.6
    environment:
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - namenode
    volumes:
      - ./spark-apps:/opt/spark-apps

  spark-worker-node-1:
    build: ./spark
    container_name: spark-worker-node-1
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--webui-port", "8081"]
    ports:
      - "8081:8081"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.7
    environment:
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
    volumes:
      - ./spark-apps:/opt/spark-apps
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  spark-worker-node-2:
    build: ./spark
    container_name: spark-worker-node-2
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--webui-port", "8081"]
    ports:
      - "8082:8081"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.8
    environment:
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
    volumes:
      - ./spark-apps:/opt/spark-apps
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  spark-worker-node-3:
    build: ./spark
    container_name: spark-worker-node-3
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--webui-port", "8081"]
    ports:
      - "8083:8081"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.9
    environment:
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
    volumes:
      - ./spark-apps:/opt/spark-apps
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  spark-worker-node-4:
    build: ./spark
    container_name: spark-worker-node-4
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077", "--webui-port", "8081"]
    ports:
      - "8084:8081"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.10
    environment:
      - SPARK_PUBLIC_DNS=localhost
    depends_on:
      - spark-master
    volumes:
      - ./spark-apps:/opt/spark-apps
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

volumes:
  hdfs_namenode:
  hdfs_datanode1:
  hdfs_datanode2:
  hdfs_datanode3:

networks:
  hdfs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16